### ISSUE TITLE
v0.0.1: create functional version of the tricrypto IL tracker suite

### ISSUE THREAD

**Issue by bout3fiddy** [bout3fiddy/tricrypto_impermanent_loss#3]
v0.0.1 should allow a used to

- [ ] get the value of added liquidity and the price of the tokens when liquidity was added.
- [ ] track withdrawn liquidity
- [ ] get their current positions in the liquidity pool
- [ ] get prices of tokens with respect to Tricrypto internal oracle as well as external oracle such as CoinGecko.

There is no UI here: only python scripts where a user can enter their wallet address.
